extern const GeoLayout stage11_geo[];
extern Lights1 stage11_Sand_tiles_lights;
extern Lights1 stage11_Sand_sides_lights;
extern u8 stage11_sand_tiles_indexed_ci4[];
extern u8 stage11_sand_tiles_indexed_pal_rgba16[];
extern u8 stage11_index_side_ci4[];
extern u8 stage11_index_side_pal_rgba16[];
extern Vtx stage11_Stage11_mesh_layer_1_vtx_0[24];
extern Gfx stage11_Stage11_mesh_layer_1_tri_0[];
extern Vtx stage11_Stage11_mesh_layer_1_vtx_1[48];
extern Gfx stage11_Stage11_mesh_layer_1_tri_1[];
extern Gfx mat_stage11_Sand_tiles[];
extern Gfx mat_revert_stage11_Sand_tiles[];
extern Gfx mat_stage11_Sand_sides[];
extern Gfx mat_revert_stage11_Sand_sides[];
extern Gfx stage11_Stage11_mesh_layer_1[];
