extern const GeoLayout testplane_geo[];
extern Lights1 testplane_f3dlite_material_lights;
extern u8 testplane_phantasmaid_eye_ci8[];
extern u8 testplane_phantasmaid_eye_pal_rgba16[];
extern Vtx testplane_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx testplane_Plane_001_mesh_layer_1_vtx_0[28];
extern Gfx testplane_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_testplane_f3dlite_material[];
extern Gfx mat_revert_testplane_f3dlite_material[];
extern Gfx testplane_Plane_001_mesh_layer_1[];
extern Gfx testplane_material_revert_render_settings[];
