extern const GeoLayout stage5_geo[];
extern Lights1 stage5_Grass_lights;
extern Lights1 stage5_Grass_001_lights;
extern u8 stage5_grass_tiles_rgba32[];
extern u8 stage5_grass_side_rgba16[];
extern Vtx stage5_stage_5_mesh_layer_1_vtx_0[16];
extern Gfx stage5_stage_5_mesh_layer_1_tri_0[];
extern Vtx stage5_stage_5_mesh_layer_1_vtx_1[32];
extern Gfx stage5_stage_5_mesh_layer_1_tri_1[];
extern Gfx mat_stage5_Grass[];
extern Gfx mat_stage5_Grass_001[];
extern Gfx stage5_stage_5_mesh_layer_1[];
