extern const GeoLayout stage9_geo[];
extern Lights1 stage9_Grass_lights;
extern Lights1 stage9_Grass_001_lights;
extern u8 stage9_grass_tiles_rgba32[];
extern u8 stage9_grass_side_rgba16[];
extern Vtx stage9_stage_9_mesh_layer_1_vtx_0[46];
extern Gfx stage9_stage_9_mesh_layer_1_tri_0[];
extern Vtx stage9_stage_9_mesh_layer_1_vtx_1[60];
extern Gfx stage9_stage_9_mesh_layer_1_tri_1[];
extern Gfx mat_stage9_Grass[];
extern Gfx mat_stage9_Grass_001[];
extern Gfx stage9_stage_9_mesh_layer_1[];
