extern const GeoLayout stage4_geo[];
extern Lights1 stage4_Grass_lights;
extern Lights1 stage4_Grass_001_lights;
extern u8 stage4_grass_tiles_rgba32[];
extern u8 stage4_grass_side_rgba16[];
extern Vtx stage4_stage_4_mesh_layer_1_vtx_0[53];
extern Gfx stage4_stage_4_mesh_layer_1_tri_0[];
extern Vtx stage4_stage_4_mesh_layer_1_vtx_1[60];
extern Gfx stage4_stage_4_mesh_layer_1_tri_1[];
extern Gfx mat_stage4_Grass[];
extern Gfx mat_stage4_Grass_001[];
extern Gfx stage4_stage_4_mesh_layer_1[];
