extern const GeoLayout stage3_geo[];
extern Lights1 stage3_Grass_lights;
extern Lights1 stage3_Grass_001_lights;
extern u8 stage3_grass_tiles_rgba32[];
extern u8 stage3_grass_side_rgba16[];
extern Vtx stage3_stage_3_mesh_layer_1_vtx_0[46];
extern Gfx stage3_stage_3_mesh_layer_1_tri_0[];
extern Vtx stage3_stage_3_mesh_layer_1_vtx_1[60];
extern Gfx stage3_stage_3_mesh_layer_1_tri_1[];
extern Gfx mat_stage3_Grass[];
extern Gfx mat_stage3_Grass_001[];
extern Gfx stage3_stage_3_mesh_layer_1[];
