extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern const GeoLayout bob_area_5_geo[];
extern const GeoLayout bob_area_5[];
extern const Collision bob_area_5_collision[];
extern const MacroObject bob_area_5_macro_objs[];
extern const GeoLayout bob_area_6_geo[];
extern const GeoLayout bob_area_6[];
extern const Collision bob_area_6_collision[];
extern const MacroObject bob_area_6_macro_objs[];
extern const GeoLayout bob_area_7_geo[];
extern const GeoLayout bob_area_7[];
extern const Collision bob_area_7_collision[];
extern const MacroObject bob_area_7_macro_objs[];
extern const GeoLayout bob_area_8_geo[];
extern const GeoLayout bob_area_8[];
extern const Collision bob_area_8_collision[];
extern const MacroObject bob_area_8_macro_objs[];
extern const GeoLayout bob_area_9_geo[];
extern const GeoLayout bob_area_9[];
extern const Collision bob_area_9_collision[];
extern const MacroObject bob_area_9_macro_objs[];
extern const GeoLayout bob_area_10_geo[];
extern const GeoLayout bob_area_10[];
extern const Collision bob_area_10_collision[];
extern const MacroObject bob_area_10_macro_objs[];
extern Lights1 bob_dl_Goal_land_lights;
extern Lights1 bob_dl_f3dlite_material_019_lights;
extern u8 bob_dl_fwater_i4[];
extern u8 bob_dl_Frushedwater_i4[];
extern u8 bob_dl_islandsiiil_ia4[];
extern u8 bob_dl_island2sil_ia4[];
extern u8 bob_dl_cloudsil_ia4[];
extern u8 bob_dl_cloudisl2_ia4[];
extern u8 bob_dl_gggg_i8[];
extern u8 bob_dl_smoothtunnelrock_i8[];
extern u8 bob_dl_dreamlandfringe_ia8[];
extern u8 bob_dl_altgrass_rgba16[];
extern u8 bob_dl_RMGP01_5eaa6816_4_i8[];
extern u8 bob_dl_frond_rgba16[];
extern u8 bob_dl_RMGP01_bf2070ac_14_ia8[];
extern u8 bob_dl_RMGP01_93aca4b2_14_ia8[];
extern u8 bob_dl_yippeeee_ci8[];
extern u8 bob_dl_yippeeee_pal_rgba16[];
extern u8 bob_dl_m_ia4[];
extern u8 bob_dl_p_ia4[];
extern u8 bob_dl_fiiire_rgba16[];
extern Vtx bob_dl_visuals_009_mesh_layer_5_vtx_0[52];
extern Gfx bob_dl_visuals_009_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_009_mesh_layer_7_vtx_0[64];
extern Gfx bob_dl_visuals_009_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_009_mesh_layer_7_vtx_1[64];
extern Gfx bob_dl_visuals_009_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_009_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_009_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_009_mesh_layer_7_vtx_3[12];
extern Gfx bob_dl_visuals_009_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_009_mesh_layer_1_vtx_0[110];
extern Gfx bob_dl_visuals_009_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_009_mesh_layer_6_vtx_0[48];
extern Gfx bob_dl_visuals_009_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_001_mesh_layer_5_vtx_0[52];
extern Gfx bob_dl_visuals_001_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_001_mesh_layer_7_vtx_0[64];
extern Gfx bob_dl_visuals_001_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_001_mesh_layer_7_vtx_1[64];
extern Gfx bob_dl_visuals_001_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_001_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_001_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_001_mesh_layer_7_vtx_3[12];
extern Gfx bob_dl_visuals_001_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_001_mesh_layer_1_vtx_0[110];
extern Gfx bob_dl_visuals_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_001_mesh_layer_6_vtx_0[48];
extern Gfx bob_dl_visuals_001_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_002_mesh_layer_5_vtx_0[53];
extern Gfx bob_dl_visuals_002_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_002_mesh_layer_7_vtx_0[32];
extern Gfx bob_dl_visuals_002_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_002_mesh_layer_7_vtx_1[64];
extern Gfx bob_dl_visuals_002_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_002_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_002_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_002_mesh_layer_7_vtx_3[8];
extern Gfx bob_dl_visuals_002_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_002_mesh_layer_1_vtx_0[90];
extern Gfx bob_dl_visuals_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_002_mesh_layer_1_vtx_1[45];
extern Gfx bob_dl_visuals_002_mesh_layer_1_tri_1[];
extern Vtx bob_dl_visuals_002_mesh_layer_6_vtx_0[46];
extern Gfx bob_dl_visuals_002_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_002_mesh_layer_4_vtx_0[214];
extern Gfx bob_dl_visuals_002_mesh_layer_4_tri_0[];
extern Vtx bob_dl_visuals_003_mesh_layer_5_vtx_0[52];
extern Gfx bob_dl_visuals_003_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_003_mesh_layer_7_vtx_0[64];
extern Gfx bob_dl_visuals_003_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_003_mesh_layer_7_vtx_1[64];
extern Gfx bob_dl_visuals_003_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_003_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_003_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_003_mesh_layer_7_vtx_3[12];
extern Gfx bob_dl_visuals_003_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_003_mesh_layer_1_vtx_0[173];
extern Gfx bob_dl_visuals_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_003_mesh_layer_1_vtx_1[38];
extern Gfx bob_dl_visuals_003_mesh_layer_1_tri_1[];
extern Vtx bob_dl_visuals_003_mesh_layer_1_vtx_2[26];
extern Gfx bob_dl_visuals_003_mesh_layer_1_tri_2[];
extern Vtx bob_dl_visuals_003_mesh_layer_6_vtx_0[72];
extern Gfx bob_dl_visuals_003_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_004_mesh_layer_5_vtx_0[53];
extern Gfx bob_dl_visuals_004_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_004_mesh_layer_7_vtx_0[32];
extern Gfx bob_dl_visuals_004_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_004_mesh_layer_7_vtx_1[64];
extern Gfx bob_dl_visuals_004_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_004_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_004_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_004_mesh_layer_7_vtx_3[8];
extern Gfx bob_dl_visuals_004_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_004_mesh_layer_1_vtx_0[90];
extern Gfx bob_dl_visuals_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_004_mesh_layer_1_vtx_1[45];
extern Gfx bob_dl_visuals_004_mesh_layer_1_tri_1[];
extern Vtx bob_dl_visuals_004_mesh_layer_6_vtx_0[46];
extern Gfx bob_dl_visuals_004_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_004_mesh_layer_4_vtx_0[214];
extern Gfx bob_dl_visuals_004_mesh_layer_4_tri_0[];
extern Vtx bob_dl_visuals_005_mesh_layer_5_vtx_0[53];
extern Gfx bob_dl_visuals_005_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_005_mesh_layer_7_vtx_0[32];
extern Gfx bob_dl_visuals_005_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_005_mesh_layer_7_vtx_1[64];
extern Gfx bob_dl_visuals_005_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_005_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_005_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_005_mesh_layer_7_vtx_3[8];
extern Gfx bob_dl_visuals_005_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_005_mesh_layer_1_vtx_0[90];
extern Gfx bob_dl_visuals_005_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_005_mesh_layer_1_vtx_1[45];
extern Gfx bob_dl_visuals_005_mesh_layer_1_tri_1[];
extern Vtx bob_dl_visuals_005_mesh_layer_6_vtx_0[46];
extern Gfx bob_dl_visuals_005_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_005_mesh_layer_4_vtx_0[214];
extern Gfx bob_dl_visuals_005_mesh_layer_4_tri_0[];
extern Vtx bob_dl_visuals_006_mesh_layer_5_vtx_0[52];
extern Gfx bob_dl_visuals_006_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_006_mesh_layer_7_vtx_0[64];
extern Gfx bob_dl_visuals_006_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_006_mesh_layer_7_vtx_1[64];
extern Gfx bob_dl_visuals_006_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_006_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_006_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_006_mesh_layer_7_vtx_3[12];
extern Gfx bob_dl_visuals_006_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_006_mesh_layer_1_vtx_0[172];
extern Gfx bob_dl_visuals_006_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_006_mesh_layer_1_vtx_1[38];
extern Gfx bob_dl_visuals_006_mesh_layer_1_tri_1[];
extern Vtx bob_dl_visuals_006_mesh_layer_1_vtx_2[26];
extern Gfx bob_dl_visuals_006_mesh_layer_1_tri_2[];
extern Vtx bob_dl_visuals_006_mesh_layer_6_vtx_0[72];
extern Gfx bob_dl_visuals_006_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_007_mesh_layer_5_vtx_0[52];
extern Gfx bob_dl_visuals_007_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_007_mesh_layer_7_vtx_0[64];
extern Gfx bob_dl_visuals_007_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_007_mesh_layer_7_vtx_1[64];
extern Gfx bob_dl_visuals_007_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_007_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_007_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_007_mesh_layer_7_vtx_3[12];
extern Gfx bob_dl_visuals_007_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_007_mesh_layer_1_vtx_0[172];
extern Gfx bob_dl_visuals_007_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_007_mesh_layer_6_vtx_0[72];
extern Gfx bob_dl_visuals_007_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_008_mesh_layer_5_vtx_0[52];
extern Gfx bob_dl_visuals_008_mesh_layer_5_tri_0[];
extern Vtx bob_dl_visuals_008_mesh_layer_7_vtx_0[32];
extern Gfx bob_dl_visuals_008_mesh_layer_7_tri_0[];
extern Vtx bob_dl_visuals_008_mesh_layer_7_vtx_1[32];
extern Gfx bob_dl_visuals_008_mesh_layer_7_tri_1[];
extern Vtx bob_dl_visuals_008_mesh_layer_7_vtx_2[4];
extern Gfx bob_dl_visuals_008_mesh_layer_7_tri_2[];
extern Vtx bob_dl_visuals_008_mesh_layer_7_vtx_3[24];
extern Gfx bob_dl_visuals_008_mesh_layer_7_tri_3[];
extern Vtx bob_dl_visuals_008_mesh_layer_1_vtx_0[142];
extern Gfx bob_dl_visuals_008_mesh_layer_1_tri_0[];
extern Vtx bob_dl_visuals_008_mesh_layer_1_vtx_1[45];
extern Gfx bob_dl_visuals_008_mesh_layer_1_tri_1[];
extern Vtx bob_dl_visuals_008_mesh_layer_6_vtx_0[46];
extern Gfx bob_dl_visuals_008_mesh_layer_6_tri_0[];
extern Vtx bob_dl_visuals_008_mesh_layer_4_vtx_0[214];
extern Gfx bob_dl_visuals_008_mesh_layer_4_tri_0[];
extern Vtx bob_dl_Plane_019_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_019_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_019_mesh_layer_1_vtx_1[16];
extern Gfx bob_dl_Plane_019_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_019_mesh_layer_1_vtx_2[360];
extern Gfx bob_dl_Plane_019_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_019_mesh_layer_4_vtx_0[4];
extern Gfx bob_dl_Plane_019_mesh_layer_4_tri_0[];
extern Vtx bob_dl_Plane_019_mesh_layer_4_vtx_1[4];
extern Gfx bob_dl_Plane_019_mesh_layer_4_tri_1[];
extern Vtx bob_dl_Plane_019_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Plane_019_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_cozieswater_001_layer5_area1[];
extern Gfx mat_revert_bob_dl_cozieswater_001_layer5_area1[];
extern Gfx mat_bob_dl_f3dlite_material_010[];
extern Gfx mat_revert_bob_dl_f3dlite_material_010[];
extern Gfx mat_bob_dl_f3dlite_material_011[];
extern Gfx mat_revert_bob_dl_f3dlite_material_011[];
extern Gfx mat_bob_dl_f3dlite_material_012[];
extern Gfx mat_revert_bob_dl_f3dlite_material_012[];
extern Gfx mat_bob_dl_f3dlite_material_013[];
extern Gfx mat_revert_bob_dl_f3dlite_material_013[];
extern Gfx mat_bob_dl_additive_coral_layer1[];
extern Gfx mat_revert_bob_dl_additive_coral_layer1[];
extern Gfx mat_bob_dl_grasfringe_001_layer6[];
extern Gfx mat_revert_bob_dl_grasfringe_001_layer6[];
extern Gfx mat_bob_dl_additive_woob_layer1[];
extern Gfx mat_revert_bob_dl_additive_woob_layer1[];
extern Gfx mat_bob_dl_f3dlite_material_014[];
extern Gfx mat_revert_bob_dl_f3dlite_material_014[];
extern Gfx mat_bob_dl_f3dlite_material_015[];
extern Gfx mat_revert_bob_dl_f3dlite_material_015[];
extern Gfx mat_bob_dl_f3dlite_material_016[];
extern Gfx mat_revert_bob_dl_f3dlite_material_016[];
extern Gfx mat_bob_dl_Goal_land[];
extern Gfx mat_revert_bob_dl_Goal_land[];
extern Gfx mat_bob_dl_f3dlite_material_018[];
extern Gfx mat_bob_dl_f3dlite_material_019[];
extern Gfx mat_bob_dl_f3dlite_material_020[];
extern Gfx mat_revert_bob_dl_f3dlite_material_020[];
extern Gfx mat_bob_dl_f3dlite_material_021[];
extern Gfx mat_revert_bob_dl_f3dlite_material_021[];
extern Gfx mat_bob_dl_f3dlite_material_024[];
extern Gfx mat_revert_bob_dl_f3dlite_material_024[];
extern Gfx bob_dl_visuals_009_mesh_layer_5[];
extern Gfx bob_dl_visuals_009_mesh_layer_7[];
extern Gfx bob_dl_visuals_009_mesh_layer_1[];
extern Gfx bob_dl_visuals_009_mesh_layer_6[];
extern Gfx bob_dl_visuals_001_mesh_layer_5[];
extern Gfx bob_dl_visuals_001_mesh_layer_7[];
extern Gfx bob_dl_visuals_001_mesh_layer_1[];
extern Gfx bob_dl_visuals_001_mesh_layer_6[];
extern Gfx bob_dl_visuals_002_mesh_layer_5[];
extern Gfx bob_dl_visuals_002_mesh_layer_7[];
extern Gfx bob_dl_visuals_002_mesh_layer_1[];
extern Gfx bob_dl_visuals_002_mesh_layer_6[];
extern Gfx bob_dl_visuals_002_mesh_layer_4[];
extern Gfx bob_dl_visuals_003_mesh_layer_5[];
extern Gfx bob_dl_visuals_003_mesh_layer_7[];
extern Gfx bob_dl_visuals_003_mesh_layer_1[];
extern Gfx bob_dl_visuals_003_mesh_layer_6[];
extern Gfx bob_dl_visuals_004_mesh_layer_5[];
extern Gfx bob_dl_visuals_004_mesh_layer_7[];
extern Gfx bob_dl_visuals_004_mesh_layer_1[];
extern Gfx bob_dl_visuals_004_mesh_layer_6[];
extern Gfx bob_dl_visuals_004_mesh_layer_4[];
extern Gfx bob_dl_visuals_005_mesh_layer_5[];
extern Gfx bob_dl_visuals_005_mesh_layer_7[];
extern Gfx bob_dl_visuals_005_mesh_layer_1[];
extern Gfx bob_dl_visuals_005_mesh_layer_6[];
extern Gfx bob_dl_visuals_005_mesh_layer_4[];
extern Gfx bob_dl_visuals_006_mesh_layer_5[];
extern Gfx bob_dl_visuals_006_mesh_layer_7[];
extern Gfx bob_dl_visuals_006_mesh_layer_1[];
extern Gfx bob_dl_visuals_006_mesh_layer_6[];
extern Gfx bob_dl_visuals_007_mesh_layer_5[];
extern Gfx bob_dl_visuals_007_mesh_layer_7[];
extern Gfx bob_dl_visuals_007_mesh_layer_1[];
extern Gfx bob_dl_visuals_007_mesh_layer_6[];
extern Gfx bob_dl_visuals_008_mesh_layer_5[];
extern Gfx bob_dl_visuals_008_mesh_layer_7[];
extern Gfx bob_dl_visuals_008_mesh_layer_1[];
extern Gfx bob_dl_visuals_008_mesh_layer_6[];
extern Gfx bob_dl_visuals_008_mesh_layer_4[];
extern Gfx bob_dl_Plane_019_mesh_layer_1[];
extern Gfx bob_dl_Plane_019_mesh_layer_4[];
extern Gfx bob_dl_Plane_019_mesh_layer_5[];
