extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const MacroObject wf_area_3_macro_objs[];
extern const GeoLayout wf_area_4_geo[];
extern const GeoLayout wf_area_4[];
extern const Collision wf_area_4_collision[];
extern const MacroObject wf_area_4_macro_objs[];
extern const GeoLayout wf_area_5_geo[];
extern const GeoLayout wf_area_5[];
extern const Collision wf_area_5_collision[];
extern const MacroObject wf_area_5_macro_objs[];
extern const GeoLayout wf_area_6_geo[];
extern const GeoLayout wf_area_6[];
extern const Collision wf_area_6_collision[];
extern const MacroObject wf_area_6_macro_objs[];
extern const GeoLayout wf_area_7_geo[];
extern const GeoLayout wf_area_7[];
extern const Collision wf_area_7_collision[];
extern const MacroObject wf_area_7_macro_objs[];
extern const GeoLayout wf_area_8_geo[];
extern const GeoLayout wf_area_8[];
extern const Collision wf_area_8_collision[];
extern const MacroObject wf_area_8_macro_objs[];
extern const GeoLayout wf_area_9_geo[];
extern const GeoLayout wf_area_9[];
extern const Collision wf_area_9_collision[];
extern const MacroObject wf_area_9_macro_objs[];
extern const GeoLayout wf_area_10_geo[];
extern const GeoLayout wf_area_10[];
extern const Collision wf_area_10_collision[];
extern const MacroObject wf_area_10_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_009_lights;
extern u8 wf_dl_and_rgba16[];
extern u8 wf_dl_sand_rgba16[];
extern u8 wf_dl_gggg_i8[];
extern u8 wf_dl_smoothtunnelrock_i8[];
extern Vtx wf_dl_visuals_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_001_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_001_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_001_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_001_mesh_layer_1_vtx_1[208];
extern Gfx wf_dl_visuals_001_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_002_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_002_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_002_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_002_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_002_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_003_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_003_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_003_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_003_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_003_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_003_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_004_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_004_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_004_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_004_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_004_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_004_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_005_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_005_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_005_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_005_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_005_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_005_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_006_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_006_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_006_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_006_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_006_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_006_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_007_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_007_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_007_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_007_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_007_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_007_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_008_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_008_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_008_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_008_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_008_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_008_mesh_layer_1_tri_1[];
extern Vtx wf_dl_visuals_009_mesh_layer_5_vtx_0[135];
extern Gfx wf_dl_visuals_009_mesh_layer_5_tri_0[];
extern Vtx wf_dl_visuals_009_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_009_mesh_layer_1_tri_0[];
extern Vtx wf_dl_visuals_009_mesh_layer_1_vtx_1[152];
extern Gfx wf_dl_visuals_009_mesh_layer_1_tri_1[];
extern Gfx mat_wf_dl_cozieswater_001_layer5_area1[];
extern Gfx mat_revert_wf_dl_cozieswater_001_layer5_area1[];
extern Gfx mat_wf_dl_f3dlite_material_009[];
extern Gfx mat_wf_dl_additive_coral_layer1[];
extern Gfx mat_revert_wf_dl_additive_coral_layer1[];
extern Gfx wf_dl_visuals_mesh_layer_5[];
extern Gfx wf_dl_visuals_mesh_layer_1[];
extern Gfx wf_dl_visuals_001_mesh_layer_5[];
extern Gfx wf_dl_visuals_001_mesh_layer_1[];
extern Gfx wf_dl_visuals_002_mesh_layer_5[];
extern Gfx wf_dl_visuals_002_mesh_layer_1[];
extern Gfx wf_dl_visuals_003_mesh_layer_5[];
extern Gfx wf_dl_visuals_003_mesh_layer_1[];
extern Gfx wf_dl_visuals_004_mesh_layer_5[];
extern Gfx wf_dl_visuals_004_mesh_layer_1[];
extern Gfx wf_dl_visuals_005_mesh_layer_5[];
extern Gfx wf_dl_visuals_005_mesh_layer_1[];
extern Gfx wf_dl_visuals_006_mesh_layer_5[];
extern Gfx wf_dl_visuals_006_mesh_layer_1[];
extern Gfx wf_dl_visuals_007_mesh_layer_5[];
extern Gfx wf_dl_visuals_007_mesh_layer_1[];
extern Gfx wf_dl_visuals_008_mesh_layer_5[];
extern Gfx wf_dl_visuals_008_mesh_layer_1[];
extern Gfx wf_dl_visuals_009_mesh_layer_5[];
extern Gfx wf_dl_visuals_009_mesh_layer_1[];
