extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_025_lights;
extern Vtx wf_dl_visuals_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_visuals_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material_025[];
extern Gfx wf_dl_visuals_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
