extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl_f3dlite_material_002_lights;
extern Lights1 jrb_dl_f3dlite_material_003_lights;
extern Lights1 jrb_dl_f3dlite_material_004_lights;
extern Lights1 jrb_dl_f3dlite_material_005_lights;
extern Lights1 jrb_dl_f3dlite_material_006_lights;
extern u8 jrb_dl_cunk_ia8[];
extern u8 jrb_dl_boens_ci8[];
extern u8 jrb_dl_boens_pal_rgba16[];
extern u8 jrb_dl_RMGP01_fed5bea4_14_ci8[];
extern u8 jrb_dl_RMGP01_fed5bea4_14_pal_rgba16[];
extern u8 jrb_dl_and_ci8[];
extern u8 jrb_dl_and_pal_rgba16[];
extern u8 jrb_dl_RMGP01_42c04f35_14_mip3_ci8[];
extern u8 jrb_dl_RMGP01_42c04f35_14_mip3_pal_rgba16[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_0[72];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_1[20];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_2[12];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_3[18];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_4[27];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_4[];
extern Gfx mat_jrb_dl_f3dlite_material_002[];
extern Gfx mat_jrb_dl_f3dlite_material_003[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_003[];
extern Gfx mat_jrb_dl_f3dlite_material_004[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_004[];
extern Gfx mat_jrb_dl_f3dlite_material_005[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_005[];
extern Gfx mat_jrb_dl_f3dlite_material_006[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_006[];
extern Gfx jrb_dl_Plane_mesh_layer_1[];
extern Gfx jrb_dl_material_revert_render_settings[];
