#include "actors/stage10/texscroll.inc.h"
#include "actors/stage9/texscroll.inc.h"
#include "actors/stage8/texscroll.inc.h"
#include "actors/stage7/texscroll.inc.h"
#include "actors/stage6/texscroll.inc.h"
#include "actors/boost_ring/texscroll.inc.h"
#include "actors/boost_vertical/texscroll.inc.h"
#include "actors/stage5/texscroll.inc.h"
#include "actors/stage4/texscroll.inc.h"
#include "actors/stage3/texscroll.inc.h"
#include "actors/stage2/texscroll.inc.h"
#include "actors/stage1/texscroll.inc.h"
extern void scroll_textures_group0();
