#include "levels/wf/stage19/texscroll.inc.h"
#include "levels/wf/stage18/texscroll.inc.h"
#include "levels/wf/stage16/texscroll.inc.h"
#include "levels/wf/stage15/texscroll.inc.h"
#include "levels/wf/rotater/texscroll.inc.h"
#include "levels/wf/stage14/texscroll.inc.h"
#include "levels/wf/stage13/texscroll.inc.h"
#include "levels/wf/stage12/texscroll.inc.h"
#include "levels/wf/texscroll.inc.h"
extern void scroll_textures_wf();
