extern const GeoLayout stage8_geo[];
extern Lights1 stage8_Grass_lights;
extern Lights1 stage8_Grass_001_lights;
extern u8 stage8_grass_tiles_rgba32[];
extern u8 stage8_grass_side_rgba16[];
extern Vtx stage8_stage8_mesh_layer_1_vtx_0[28];
extern Gfx stage8_stage8_mesh_layer_1_tri_0[];
extern Vtx stage8_stage8_mesh_layer_1_vtx_1[32];
extern Gfx stage8_stage8_mesh_layer_1_tri_1[];
extern Gfx mat_stage8_Grass[];
extern Gfx mat_stage8_Grass_001[];
extern Gfx stage8_stage8_mesh_layer_1[];
